<form method="post">
    <hr>
    <p>Edit employee information below. Please enter the employee code to edit.</p>

    <label for="editCode">Employee Code</label>
    <input name="editCode" type="text" id="editCode">
    <button type="submit">Find Employee</button>
</form>

<?php
if ($_SERVER["REQUEST_METHOD"] == "POST") {
    $editCode = $_POST["editCode"];
    $employeeToEdit = findAnEmployeeByCode($financeDepartments, $editCode);

    if ($employeeToEdit) {
        ?>
        <form method="post">
            <input type="hidden" name="editCode" value="<?= $editCode; ?>">
            <label for="editFullName">Full name</label>
            <input name="editFullName" type="text" id="editFullName" value="<?= $employeeToEdit['fullName']; ?>">
            <br>
            <label for="editPosition">Position</label>
            <input name="editPosition" type="text" id="editPosition" value="<?= $employeeToEdit['position']; ?>">
            <br>
            <label for="editSalary">Salary</label>
            <input name="editSalary" type="text" id="editSalary" value="<?= $employeeToEdit['salary']; ?>">
            <br>
            <label for="editChildrenAmount">Amount of children</label>
            <input name="editChildrenAmount" type="text" id="editChildrenAmount" value="<?= $employeeToEdit['childrenAmount']; ?>">
            <br>
            <label for="editWorkExperience">Work experience</label>
            <input name="editWorkExperience" type="text" id="editWorkExperience" value="<?= $employeeToEdit['workExperience']; ?>">
            <br />
            <br />
            <button type="submit">Save Changes</button>
        </form>
        <?php
    } else {
        echo "Employee not found with code: $editCode";
    }
}


function findAnEmployeeByCode($array, $code)
{
    foreach ($array as $employee) {
        if ($employee['code'] == $code) {
            return $employee;
        }
    }
    return false;
}
?>
